version: "3.7"

networks: 
  devops:
    driver: bridge

services:

  customer:
    image: ciceroreis/devops
    container_name: customer
    restart: unless-stopped
    working_dir: /var/www
    volumes: 
      - ./:/var/www
    networks: 
      - devops
