version: "3.7"

networks: 
  devops:
    driver: bridge

services:

  nginx:
    image: nginx:1.13
    container_name: customer_nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
      - ./docker/nginx/cert.crt:/etc/nginx/certs/cert.crt
      - ./docker/nginx/cert.key:/etc/nginx/certs/cert.key
    ports:
      - 8001:80
      - 443:443
    networks:
      - devops

  customer:
    image: ciceroreis/devops
    container_name: customer
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    working_dir: /var/www
    volumes: 
      - ./:/var/www
      - ./docker/php/php.ini-development:/usr/local/etc/php/php.ini-development
      - ./docker/php/php.ini-production:/usr/local/etc/php/php.ini-production
    depends_on: 
      - redis
    networks: 
      - devops

  queue:
    image: ciceroreis/devops
    container_name: customer_queue
    command: php artisan queue:work
    restart: unless-stopped
    volumes:
      - ./:/var/www
    networks:
      - devops

  redis:
    image: redis:alpine
    container_name: customer_redis
    volumes:
    - ./volumes/redis:/data
    networks:
      - devops
